name:                haskell-in-depth
version:             0.1.0.0
github:              "githubuser/haskell-in-depth"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-in-depth#readme>
data-files:
    - data/*.*
dependencies:
- base >= 4.7 && < 5
- mtl
- text
- fmt
- random
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
internal-libraries:
   contexts:
        source-dirs: ch02
        exposed-modules: Contexts
        other-modules: []
        dependencies:
          - mtl >=2.0 && <2.3
executables:
  haskell-in-depth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-in-depth
  person-text:
    main: text-show.hs
    source-dirs: ch02/person
    other-modules: Person
    dependencies:
        - text-show
  expr-simple:
    main: Main.hs
    source-dirs: expr
    exposed-modules: Expr
    dependencies:
        - text-show
  evalrpn1:
    source-dirs: expr/rpn
    main: evalrpn1.hs
    other-modules: [EvalRPN]
    dependencies:
    - mtl
tests:
  haskell-in-depth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-in-depth
    # Chapter 2
  typeclass-test:
    source-dirs: test
    main: TypeClass-test.hs
    other-modules: []
    dependencies:
    - haskell-in-depth
    - random >=1.2 && <1.3
